export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Fast Transfers ',
    headline: 'With a couple of clicks you can send or receive money',
    description:'This app is very intuitive and easy to use which makes it perfect for all people',
    buttonLabel: 'Learn More',
    imgStart: false,
    img: require('../../images/imagen1.svg').default,
    alt:'about',
    dark: true,
    primary: true,
    darkText: false
}
export const homeObjTwo = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'International Chilean Online Bank',
    headline: 'Unlimited Transactions with no fees nor Issues',
    description:'By using our app you can send and receive transactions in an easy way to your family and friends with no extra fees or worries about hidden transactions',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../images/imagen2.svg').default,
    alt:'Car',
    dark: false,
    primary: false,
    darkText: true,
}


export const homeObjThree = {
    id: 'signup',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Get discounts!',
    headline: 'Multiple Benefits for using this Online Card',
    description:'You can receive some cashback at the moment of buying online in some online stores',
    buttonLabel: 'Learn More',
    imgStart: false,
    img: require('../../images/imagen3.svg').default,
    alt:'Car',
    dark: true,
    primary: true,
    darkText: false,
}
export const homeObjFour = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Closeness to this Online Bank',
    headline: 'We are here for you 24/7',
    description:'Customer Service is easy to reach out. We have two fully cooperative and responsive ways to communicate with you in a fast way.',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/imagen4.svg').default,
    alt:'Car',
    dark: false,
    primary: false,
    darkText: true,
}

